- name: Configure AAP
  hosts: localhost
  gather_facts: false    
  tasks:
    - name: Update project
      ansible.builtin.include_vars:
        dir: "config/project"
        extensions:
          - 'yml'

    - name: Load environment-specific configuration
      ansible.builtin.include_vars:
        dir: "config/{{ version }}"
        extensions:
          - 'yml'
      # Example: Run with `ansible-playbook playbook.yml -e "env=prod"`

    - name: Run the main configuration role
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        dispatch_include_wildcard_vars: true
