---
- name: Apply AAP 2.6 Controller Settings
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    #- configs/auth.yml       
    - configs/demo_template.yml
  roles:
    - role: infra.aap_configuration.job_templates
