---
controller_templates:
  - name: "V2 Template"
    description: "V2"
    image: "Default execution environment" # ee-supported-rhel9:latest # Execution environment
    inventory: "Demo Inventory"
    project: "{{ env }}"
    playbook: "v2.yml"
    job_type: "run"
    organization: "{{ env }}"
    #become_enabled: true
    credentials: "Demo Credential"
    #extra_vars:
    #survey_enabled: false
